- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: "{{ openssl_private_key_path }}"

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ openssl_csr_path }}"
    privatekey_path: "{{ openssl_private_key_path }}"
    common_name: "{{ openssl_domains[0] }}"
    email_address: "{{ openssl_email_address | default(omit) }}"
    country_name: "{{ openssl_country_name | default(omit) }}"
    locality_name: "{{ openssl_locality_name | default(omit) }}"
    organization_name: "{{ openssl_organization_name | default(omit) }}"
    organizational_unit_name: "{{ openssl_organizational_unit_name | default(omit) }}"
    state_or_province_name: "{{ openssl_state_or_province_name | default(omit) }}"
    subject_alt_name: "{{ openssl_domains | map('regex_replace', '^', 'DNS:') | list | default(omit) }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ openssl_certificate_path }}"
    privatekey_path: "{{ openssl_private_key_path }}"
    csr_path: "{{ openssl_csr_path }}"
    provider: selfsigned
